export const API_ENDPOINTS = {
  HEADER_LOGO: "/api/logos/category/website-logo", // adjust if endpoint differs
  HOME_BANNERS: "/api/banners",
  ARTICLE_BY_SLUG: (slug) => `/api/articles/${slug}`,
  HOME_ABOUT: "/api/articles/about-pwd",
  CONTACT_NUMBER: "/api/web-translations/contact",
  FLASH_ALERTS: "/api/notification-home",
  SERVICES: "/api/wing-masters",
  OFFICIAL_SITES:"/api/logos/category/official-sites",
  MENUS: "/api/menus",
  KLA15_QUESTIONS: "/api/kla15-questions",
  KLA_PROCEEDINGS: "/api/kla_proceedings",
  CHIEF_MINISTERS: "/api/chief_ministers",
  MADRAS_COUNCIL: "/api/madras_council",
  FORMER_SECRETARIES: "/api/former_secretaries",
  SYNOPSIS: "/api/synopsis",
  GLEANING: "/api/gleaning",
  STATISTICAL_ANALYSIS: "/api/statistical_analysis",
  PRESIDENTS_RULE: "/api/presidents_rule",
  PVT_MEMBER_RESOLUTIONS: "/api/pvt_member_resolutions",
  BUDGET_SPEECHES: "/api/budget_speech",
  TENDERS: "/api/tenders",
  KLA_DURATION: "/api/kla_duration",
  MEMBER_CONTACT: "/api/member_contact",
};
