// Central registry of filters extracted from Filter.jsx to avoid exporting constants
// from a file that also exports React components (fast-refresh friendly).
export const FILTER_REGISTRY = {
  SEARCH_BULLETIN: {
    key: "SEARCH_BULLETIN",
    label: "Search Bulletin By",
    type: "custom",
    defaultValue: { type: "name", query: "" },
  },

  KLA: {
    key: "KLA",
    label: "KLA",
    type: "select",
    multiple: false,
    // Use numeric values for options so callers can read kla_id reliably
    options: [
      { value: 15, label: "15th KLA" },
      { value: 14, label: "14th KLA" },
      { value: 13, label: "13th KLA" },
      { value: 12, label: "12th KLA" },
      { value: 11, label: "11th KLA" },
    ],
    // default to 14 (as requested)
    defaultValue: 14,
  },
  GENDER: {
    key: "GENDER",
    label: "LEGISLATIVE ASSEMBLY",
    type: "select",
    multiple: false,
    options: ["Sitting Members", "Woman Members", "Member Profile"],
  },
  SESSION: {
    key: "SESSION",
    label: "Session",
    type: "select",
    multiple: false,
    options: [
      "Session 1",
      "Session 2",
      "Session 3",
      "Session 4",
      "Session 5",
      "Session 6",
      "Session 7",
      "Session 8",
      "Session 9",
    ],
  },
  SESSION_TYPE: {
    key: "SESSION_TYPE",
    label: "Session Number",
    type: "select",
    multiple: false,
    options: ["All", "Session 1", "Session 2", "Session 3"],
  },
  BILL_TYPE: {
    key: "BILL_TYPE",
    label: "Bill Type",
    type: "select",
    multiple: false,
    options: ["All", "Government Bill", "Private Bill"],
  },
  BILL_CATEGORY: {
    key: "BILL_CATEGORY",
    label: "Bill Category",
    type: "select",
    multiple: false,
    options: ["All", "Original Bill", "Ammendment Bill", "Appropriation Bills"],
  },
  BILL_STATUS: {
    key: "BILL_STATUS",
    label: "Bill Status",
    type: "select",
    multiple: false,
    options: [
      "All",
      "Published",
      "Introduced",
      "Referred To",
      "Passed",
      "Assented",
      "Withdrawn",
      "Withheld",
      "Lapsed",
      "Removed",
    ],
  },

  ORDINANCES_TYPE: {
    key: "   ORDINANCES_TYPE",
    label: "  Ordinances Type",
    type: "select",
    multiple: false,
    options: ["All", "Ordinances Bill", "Private Bill"],
  },
  ORDINANCES_CATEGORY: {
    key: "   ORDINANCES_CATEGORY",
    label: "Ordinances Category",
    type: "select",
    multiple: false,
    options: ["Original Bill", "Ammendment Bill", "Appropriation Bills"],
  },
  ORDINANCES_STATUS: {
    key: "  ORDINANCES_STATUS",
    label: "Ordinances Status",
    type: "select",
    multiple: false,
    options: [
      "All",
      "Published",
      "Introduced",
      "Refered To",
      "Passed",
      "Assented",
      "Withdrawn",
      "removed",
    ],
  },

  OPINION_TYPE: {
    key: "   OPINION_TYPE",
    label: "  Opinion Type",
    type: "select",
    multiple: false,
    options: ["All", "Ordinances Bill", "Private Bill"],
  },
  OPINION_CATEGORY: {
    key: "   OPINION_CATEGORY",
    label: "Opinion Category",
    type: "select",
    multiple: false,
    options: ["Opinion Bill", "Opinion Bill", "Appropriation Bills"],
  },
  OPINION_STATUS: {
    key: "  OPINION_STATUS",
    label: "Opinion Category",
    type: "select",
    multiple: false,
    options: [
      "All",
      "Published",
      "Introduced",
      "Refered To",
      "Passed",
      "Assented",
      "Withdrawn",
      "removed",
    ],
  },

  MEMBER: {
    key: "MEMBER",
    label: "Member",
    type: "select",
    multiple: false,
    options: ["Member 1", "Member 2", "Memeber 3"],
  },
  CHAIRMAN: {
    key: "CHAIRMAN",
    label: "Chairman",
    type: "select",
    multiple: false,
    options: ["Chairman 1", "Chairman 2", "Chairman 3"],
  },
  MINISTER: {
    key: "MINISTER",
    label: "Minister",
    type: "select",
    multiple: false,
    options: ["Minister 1", "Minister 2", "Minister 3"],
  },
  DEPARTMENT: {
    key: "DEPARTMENT",
    label: "Department",
    type: "select",
    multiple: false,
    options: ["Department 1", "Department 2", "Department 3"],
  },
  CATEGORY: {
    key: "CATEGORY",
    label: "Category",
    type: "select",
    multiple: false,
    options: ["Category 1", "Category 2", "Category 3"],
  },
  QUESTION_TYPE: {
    key: "QUESTION_TYPE",
    label: "Question Type",
    type: "select",
    multiple: false,
    options: ["Quesstion 1", "Question 2", "Question 3"],
  },
  DISTRICT: {
    key: "DISTRICT",
    label: "District",
    type: "select",
    multiple: false,
    options: ["Trivandrum", "Kollam", "Malappuram", "Kannur"],
  },
  CONSTITUENCY: {
    key: "CONSTITUENCY",
    label: "Constituency",
    type: "select",
    multiple: false,
    options: ["Trivandrum", "Kollam", "Malappuram", "Kannur"],
  },
  PARTY: {
    key: "PARTY",
    label: "Party",
    type: "select",
    multiple: false,
    options: ["UDF", "LDF"],
  },
  SUBJECT: {
    key: "SUBJECT",
    label: "Subject",
    type: "select",
    multiple: false,
    options: [],
  },
  MUNICIPALITY: {
    key: "MUNICIPALITY",
    label: "Municipality",
    type: "select",
    multiple: false,
    options: ["Trivandrum", "Kollam", "Malappuram", "Kannur"],
  },
  DATE: {
    key: "DATE",
    label: "Date",
    type: "date",
    multiple: false,
  },
  YEAR: {
    key: "YEAR",
    label: "Year",
    type: "select",
    multiple: false,
    options: [
      "2024",
      "2023",
      "2022",
      "2021",
      "2020",
      "2019",
      "2018",
      "2017",
      "2016",
      "2015",
    ],
  },
  SEARCH: {
    key: "SEARCH",
    label: "Search",
    type: "text",
    multiple: false,
    placeholder: "Search",
  },
  SEARCH_NUM: {
    key: "SEARCH",
    label: "Search Number",
    type: "text",
    multiple: false,
    placeholder: "Search",
  },
  SEARCH_NAME: {
    key: "SEARCH",
    label: "Search Name",
    type: "text",
    multiple: false,
    placeholder: "Search",
  },
  COMMITTEE_CATEGORY: {
    key: "COMMITTEE_CATEGORY",
    label: "Committee Category",
    type: "select",
    multiple: false,
    options: [
      "All",
      "Advisory Committee",
      "Business Committe",
      "Subject Committees",
      "Others",
    ],
  },
  REPORT_TYPE: {
    key: "  REPORT_TYPE",
    label: "Report Type",
    type: "select",
    multiple: false,
    options: [
      "All",
      "Action Taken Report",
      "AGs Report",
      "Annual accounts",
      "Bill Reports",
      "Audit Reports",
    ],
  },
  REPORT_TITLE: {
    key: "REPORT_TITLE",
    label: "Report Title",
    type: "select",
    multiple: false,
    options: ["Report 1 ", "Report 2", "Report 3", "Report 4"],
  },
  COMMITTEE_NAME: {
    key: "COMMITTEE_NAME",
    label: "Committee Name",
    type: "select",
    multiple: false,
    options: ["Committee 1 ", "Committee 2", "Committee 3", "Committee 4"],
  },
  ORDER_BY: {
    key: "ORDER_BY",
    label: "Order By",
    type: "radio",
    multiple: false,
    options: [
      { value: "Committee", label: "Committee" },
      { value: "Members", label: "Members" },
    ],
    defaultValue: "Committee",
  },
    ANSWER_TYPE: {
    key: "ANSWER_TYPE",
    label: "Answer Type",
    type: "select",
    multiple: false,
    options: ["Answered", "Unanswered"],
  },
};

export const FILTER_KEYS = Object.keys(FILTER_REGISTRY);
